//Items
export const cards = [
    {
        id: 1,
        img: "./img/Project/project1.jpg",
        projectName: "Rock Paper Scissors",
        projectDemo: "https://frontend-projects-1.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Rock-Paper-Scissors/",
    },
    {
        id: 2,
        img: "./img/Project/project2.jpg",
        projectName: "Color Flipper",
        projectDemo: "https://frontend-projects-2.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/ColorFlipper/",
    },
    {
        id: 3,
        img: "./img/Project/project3.jpg",
        projectName: "Counter",
        projectDemo: "https://frontend-projects-3.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Counter/",
    },
    {
        id: 4,
        img: "./img/Project/project4.jpg",
        projectName: "Review Carousel",
        projectDemo: "https://frontend-projects-4.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/ReviewCarousel/",
    },
    {
        id: 5,
        img: "./img/Project/project5.jpg",
        projectName: "Responsive Navbar",
        projectDemo: "https://frontend-projects-5.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/ResponsiveNavbar/",
    },
    {
        id: 6,
        img: "./img/Project/project6.jpg",
        projectName: "Sidebar",
        projectDemo: "https://frontend-projects-6.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Sidebar/",
    },
    {
        id: 7,
        img: "./img/Project/project7.jpg",
        projectName: "Modal",
        projectDemo: "https://frontend-projects-7.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Modal/",
    },
    {
        id: 8,
        img: "./img/Project/project8.jpg",
        projectName: "Faq Page",
        projectDemo: "https://frontend-projects-8.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/faq-page/",
    },
    {
        id: 9,
        img: "./img/Project/project9.jpg",
        projectName: "Restaurant Menu Page",
        projectDemo: "https://frontend-projects-9.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/RestaurantMenu-Page/",
    },
    {
        id: 10,
        img: "./img/Project/project10.jpg",
        projectName: "Video",
        projectDemo: "https://frontend-projects-10.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Video/",
    },
    {
        id: 11,
        img: "./img/Project/project11.jpg",
        projectName: "Tabs",
        projectDemo: "https://frontend-projects-11.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Tabs/",
    },
    {
        id: 12,
        img: "./img/Project/project12.jpg",
        projectName: "Count Down",
        projectDemo: "https://frontend-projects-12.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Countdown/",
    },
    {
        id: 13,
        img: "./img/Project/project13.jpg",
        projectName: "Text Generator",
        projectDemo: "https://frontend-projects-13.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Text-generator/",
    },
    {
        id: 14,
        img: "./img/Project/project14.png",
        projectName: "Slider",
        projectDemo: "https://frontend-projects-14.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Slider/",
    },
    {
        id: 15,
        img: "./img/Project/project15.jpg",
        projectName: "Calculator",
        projectDemo: "https://frontend-projects-15.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Calculator/",
    },
    {
        id: 16,
        img: "./img/Project/project16.jpg",
        projectName: "Colorfun Animation",
        projectDemo: "https://frontend-projects-16.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Colorfun-animation/",
    },
    {
        id: 17,
        img: "./img/Project/project17.jpg",
        projectName: "Dark vs Light",
        projectDemo: "https://frontend-projects-17.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Dark-vs-Light/",
    },
    {
        id: 18,
        img: "./img/Project/project18.jpg",
        projectName: "Netflix Landing",
        projectDemo: "https://frontend-projects-18.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Netflix-Landing/",
    },
    {
        id: 19,
        img: "./img/Project/project19.jpg",
        projectName: "Paralax Scroll Website",
        projectDemo: "https://frontend-projects-19.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Paralax-scroll-website/",
    },
    {
        id: 20,
        img: "./img/Project/project20.jpg",
        projectName: "Starbucks",
        projectDemo: "https://frontend-projects-20.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Starbucks/",
    },
    {
        id: 21,
        img: "./img/Project/project21.jpg",
        projectName: "Todo List",
        projectDemo: "https://frontend-projects-21.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Todo-list/",
    },
    {
        id: 22,
        img: "./img/Project/project22.jpg",
        projectName: "Qr Code Generator",
        projectDemo: "https://frontend-projects-22.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Qr-code-generator/",
    },
    {
        id: 23,
        img: "./img/Project/project23.jpg",
        projectName: "Text To Voice Convertor",
        projectDemo: "https://frontend-project-23.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Text-to-voice-convertor/",
    },
    {
        id: 24,
        img: "./img/Project/project24.jpg",
        projectName: "Image Search Engine",
        projectDemo: "https://frontend-projects-24.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Image-search-engine/",
    },
    {
        id: 25,
        img: "./img/Project/project25.jpg",
        projectName: "Weather App",
        projectDemo: "https://frontend-projects-25.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Waether-app/",
    },
    {
        id: 26,
        img: "./img/Project/project26.jpg",
        projectName: "Airpod Animation Web",
        projectDemo: "https://frontend-projects-26.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Airpod-animation-web/",
    },
    {
        id: 27,
        img: "./img/Project/project27.jpg",
        projectName: "Heart Trail Animation",
        projectDemo: "https://frontend-projects-27.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Heart-trail-animation/",
    },
    {
        id: 28,
        img: "./img/Project/project28.jpg",
        projectName: "Real Time Character Counter",
        projectDemo: "https://frontend-projects-28.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Real-time-character-counter/",
    },
    {
        id: 29,
        img: "./img/Project/project29.jpg",
        projectName: "Digital Clock",
        projectDemo: "https://frontend-projects-29.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Digital-clock/",
    },
    {
        id: 30,
        img: "./img/Project/project30.jpg",
        projectName: "Auto Text Effect Animation",
        projectDemo: "https://frontend-projects-30.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Auto-text-effect-animation/",
    },
    {
        id: 31,
        img: "./img/Project/project31.jpg",
        projectName: "Pomodoro Timer",
        projectDemo: "https://frontend-projects-31.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Pomodoro-timer/",
    },
    {
        id: 32,
        img: "./img/Project/project32.jpg",
        projectName: "Age Calculator",
        projectDemo: "https://frontend-projects-32.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Age-calculator/",
    },
    {
        id: 33,
        img: "./img/Project/project33.jpg",
        projectName: "Random Password Generator",
        projectDemo: "https://frontend-projects-33.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Random-password-generator/",
    },
    {
        id: 34,
        img: "./img/Project/project34.jpg",
        projectName: "Tip Calculator",
        projectDemo: "https://frontend-projects-34.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Tip-calculator/",
    },
    {
        id: 35,
        img: "./img/Project/project35.jpg",
        projectName: "Dice Roll Simulator",
        projectDemo: "https://frontend-projects-35.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Dice-roll-simulator/",
    },
    {
        id: 36,
        img: "./img/Project/project36.jpg",
        projectName: "Stopwatch",
        projectDemo: "https://frontend-projects-36.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Stopwatch/",
    },
    {
        id: 37,
        img: "./img/Project/project37.jpg",
        projectName: "Weight Convertor",
        projectDemo: "https://frontend-projects-37.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Weight-convertor/",
    },
    {
        id: 38,
        img: "./img/Project/project38.jpg",
        projectName: "Temperature Convertor",
        projectDemo: "https://frontend-projects-38.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Temperature-convertor/",
    },
    {
        id: 39,
        img: "./img/Project/project39.jpg",
        projectName: "Multiplication App",
        projectDemo: "https://frontend-projects-39.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Multiplication-app/",
    },
    {
        id: 40,
        img: "./img/Project/project40.jpg",
        projectName: "Mouse Event",
        projectDemo: "https://frontend-projects-40.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Mouse-event/",
    },
    {
        id: 41,
        img: "./img/Project/project41.jpg",
        projectName: "Loan Calculator",
        projectDemo: "https://frontend-projects-41.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Loan-calculator/",
    },
    {
        id: 42,
        img: "./img/Project/project42.jpg",
        projectName: "Theme Changer",
        projectDemo: "https://frontend-projects-42.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Theme-changer/",
    },
    {
        id: 43,
        img: "./img/Project/project43.jpg",
        projectName: "Animated Website",
        projectDemo: "https://frontend-projects-43.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Animated-website/",
    },
    {
        id: 44,
        img: "./img/Project/project44.jpg",
        projectName: "Horizontal Website",
        projectDemo: "https://frontend-projects-44.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Horizontal-website/",
    },
    {
        id: 45,
        img: "./img/Project/project45.jpg",
        projectName: "Animated Website App",
        projectDemo: "https://frontend-projects-45.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Animated-website-app/",
    },
    {
        id: 46,
        img: "./img/Project/project46.jpg",
        projectName: "One Page Website",
        projectDemo: "https://frontend-projects-46.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/One-page-website/",
    },
    {
        id: 47,
        img: "./img/Project/project47.jpg",
        projectName: "Bmi Calculator",
        projectDemo: "https://frontend-projects-47.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Bmi-calculator/",
    },
    {
        id: 48,
        img: "./img/Project/project48.jpg",
        projectName: "Currency Convertor",
        projectDemo: "https://frontend-projects-48.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Currency-converter/",
    },
    {
        id: 49,
        img: "./img/Project/project49.jpg",
        projectName: "Mini Calendar",
        projectDemo: "https://frontend-projects-49.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Mini-calendar/",
    },
    {
        id: 50,
        img: "./img/Project/project50.jpg",
        projectName: "Random Images",
        projectDemo: "https://frontend-projects-50.netlify.app",
        projectCode: "https://github.com/tolqinov-o/Frontend-HTML-CSS-JS-Projects/tree/main/Random-img/",
    },
];